#!/bin/sh                                                                                                               
                                                                                                                        
if [ remove = "$1" ]; then 
	/usr/bin/signal-event addons-update

	rm -rf /opt/HELI-X*
	rm -f /opt/HELI-X*

fi

#DEBHELPER#
