#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
	cd /opt        
	rm -f /opt/HELI-X*.tar.gz
	wget https://www.heli-x.info/1912/HELI-X8.tar.gz
	tar xzf HELI-X8.tar.gz
	chown -R vdr.vdr HELI-X6
	chmod 555 HELI-X8/runHELI-X.sh
	echo "Installing demo version of HELI-X flight simulator"
fi

#DEBHELPER#

